// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoURyxcpae9iokmG_lxQiqEA-qOtwSA6E',
    appId: '1:441894256239:web:e18274f78fa99f7869579a',
    messagingSenderId: '441894256239',
    projectId: 'kithap-app',
    authDomain: 'kithap-app.firebaseapp.com',
    databaseURL: 'https://kithap-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kithap-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHefY0nFTVfA4-aM1vmArVCDpxl-CZe8M',
    appId: '1:441894256239:android:752d97d88f1388da69579a',
    messagingSenderId: '441894256239',
    projectId: 'kithap-app',
    databaseURL: 'https://kithap-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kithap-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARKK7-5DlqaFX1mtMmZX9rBDouOtP5KXw',
    appId: '1:441894256239:ios:81c6ac711e0cf74a69579a',
    messagingSenderId: '441894256239',
    projectId: 'kithap-app',
    databaseURL: 'https://kithap-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kithap-app.appspot.com',
    iosBundleId: 'com.example.kithapApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARKK7-5DlqaFX1mtMmZX9rBDouOtP5KXw',
    appId: '1:441894256239:ios:81c6ac711e0cf74a69579a',
    messagingSenderId: '441894256239',
    projectId: 'kithap-app',
    databaseURL: 'https://kithap-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kithap-app.appspot.com',
    iosBundleId: 'com.example.kithapApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoURyxcpae9iokmG_lxQiqEA-qOtwSA6E',
    appId: '1:441894256239:web:430e80ebf67585a669579a',
    messagingSenderId: '441894256239',
    projectId: 'kithap-app',
    authDomain: 'kithap-app.firebaseapp.com',
    databaseURL: 'https://kithap-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kithap-app.appspot.com',
  );

}